### ISSUE TITLE
Switch to ESLint?

### ISSUE THREAD

**Issue by kinglozzer** [bigfork/SilverStripe-Shoelace#22]
https://github.com/eslint/eslint

Haven’t actually looked into it properly, just looks a bit more “in-depth” than JSLint

**Comment by stnvh** [comment]
Seems to be more lint rule based (like scss-lint, as opposed to just chekcing for syntax errors etc.) and slower than JSHint. There would be benefits to standardising our JS further, as it's pretty much free reign at the moment.

**Comment by feejin** [comment]
I resent that comment about our JS. 
It's untamed by convention.
