### ISSUE TITLE
composer install doesn’t run post-install command

### ISSUE THREAD

**Issue by kinglozzer** [bigfork/SilverStripe-Shoelace#60]
Just creating this so you’re aware. When you create a new project, you’ll need to run `composer install` twice in a row to get the prompts for setting things up.

Composer changed so that running `composer install` when there’s no `composer.lock` present (i.e. initial install) doesn’t trigger pre/post install commands. It will run the “update” command instead.

I’ll fix it when I can be bothered. More info: https://github.com/composer/composer/issues/5066

**Comment by stnvh** [comment]
I can imagine support requests right now..
![tsunami](https://cloud.githubusercontent.com/assets/6361200/15009418/27d2d878-11de-11e6-9fcf-6e062a90b02e.gif)

**Comment by kinglozzer** [comment]
Fixed in https://github.com/bigfork/SilverStripe-Shoelace/commit/8111a1a37ee408d066652dafd067c0d4425ac359
