### ISSUE TITLE
SilverStripe 4

### ISSUE THREAD

**Issue by kinglozzer** [bigfork/SilverStripe-Shoelace#66]
I’ve separated out old/new versions into branches:

- `1` contains the old, IE8 friendly version
- `2` contains the current version (3.x)
- `3` contains a SilverStripe 4 compatible version

`master` is currently the same as `2`, once SilverStripe 4 is ready I’ll merge `3` into `master` and that can then be our default.

The main blocker is module compatibility. List of dependencies and their current status:

|Name|Status|Info|
|---|---|---|
|`bigfork/htmleditorsrcset`|:white_check_mark:|[Done](https://github.com/bigfork/htmleditorsrcset/commit/6d6294ec8dfc4c7a571a5b389f321a3b2b66f09c)|
|`feejin/silverstripe-securitytemplates`|:white_check_mark:|[Done](https://github.com/feejin/Silverstripe-SecurityTemplates/commit/532c87da0199bc02b5296f92a17fa7450b63e1de)|
|`heyday/silverstripe-responsive-images`|:white_check_mark:|[Done](https://github.com/heyday/silverstripe-responsive-images/pull/19)|
|`jonom/focuspoint`|:no_entry_sign:|Will probably be painful, much JavaScript|
|`jonom/silverstripe-share-care`|:no_entry_sign:|Will probably be painful, will need changes to opengraph module dependency too|
|`kinglozzer/bfgoogleanalytics`|:white_check_mark:|[Done](https://github.com/kinglozzer/bfgoogleanalytics)|
|`kinglozzer/htmleditornoalignment`|:no_entry_sign:|Easy|
|`kinglozzer/metatitle`|:white_check_mark:|[Done](https://github.com/kinglozzer/silverstripe-metatitle/commit/27b571f5151aba60e057c1595a39a6564448adbd)|
|`silverstripe/googlesitemaps`|:white_check_mark:|[PR merged](https://github.com/wilr/silverstripe-googlesitemaps/pull/109)|
|`silverstripe-australia/gridfieldextensions`|:white_check_mark:|Done|
|`stnvh/silverstripe-infoboxes`|:heavy_multiplication_x:|We’ll remove this|
|`unclecheese/betterbuttons`|:no_entry_sign:|Still in development, mostly there|

**Comment by feejin** [comment]
Thanks. Will stuff like better buttons and grid field tools be obsolete with 4? I've not tried alpha 3. If not, I imagine they're popular enough to be done for launch. 

We don't need info boxes. As long as we remember to do checks.

**Comment by kinglozzer** [comment]
Moved to https://github.com/bigfork/silverstripe-recipe
