### ISSUE TITLE
Use NPM for importing thirdparty libs?

### ISSUE THREAD

**Issue by AndrewHaine** [bigfork/SilverStripe-Shoelace#74]
Following from updating the way js modules are imported locally, we could also use npm to import common thirdparty libraries:

```
$ npm i superfish
```
```JS
// nav.js
import superfish from 'superfish';
```
```SCSS
// style.scss
@import 'superfish/dist/css/superfish';
```

I've created a branch updating the setup, just wondering what you think of this approach?

**Comment by kinglozzer** [comment]
Yeah that looks good, I think I only ever hard-coded `node_modules/` into the import for susy because I couldn’t get imports to work properly!
